# Generated by Django 3.2.23 on 2024-02-12 11:00

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DT7App', '0002_blogpost_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='FormsData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('services_interested', models.TextField()),
                ('message', models.TextField()),
                ('terms_and_conditions', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='FormData',
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='Body',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
