# Generated by Django 5.0.1 on 2024-07-16 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DT7App', '0003_auto_20240212_1630'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='MetaDescription',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='MetaKeywords',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='MetaTitle',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
    ]
