# Generated by Django 3.2.25 on 2025-08-13 09:47

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DT7App', '0004_blogpost_metadescription_blogpost_metakeywords_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='FAQs',
            field=ckeditor.fields.RichTextField(blank=True, help_text='Add FAQ content here (optional)', null=True),
        ),
    ]
