# Generated by Django 3.2.25 on 2025-08-13 09:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('DT7App', '0005_blogpost_faqs'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpost',
            name='FAQs',
        ),
        migrations.CreateModel(
            name='BlogFAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=255)),
                ('answer', models.TextField()),
                ('blog', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='faqs', to='DT7App.blogpost')),
            ],
        ),
    ]
