# Generated by Django 4.2.26 on 2025-11-12 12:18

import ckeditor.fields
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DT7App', '0006_auto_20250813_1526'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobPost',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False)),
                ('Title', models.CharField(default='Job Title', max_length=225)),
                ('Department', models.CharField(blank=True, max_length=100, null=True)),
                ('Location', models.CharField(blank=True, max_length=150, null=True)),
                ('Experience', models.CharField(blank=True, max_length=100, null=True)),
                ('Salary', models.CharField(blank=True, max_length=100, null=True)),
                ('JobType', models.CharField(choices=[('Full Time', 'Full Time'), ('Part Time', 'Part Time'), ('Internship', 'Internship'), ('Contract', 'Contract')], default='Full Time', max_length=50)),
                ('Body', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('PostedBy', models.CharField(blank=True, max_length=100, null=True)),
                ('PostedDate', models.DateTimeField(default=datetime.datetime.now)),
                ('Deadline', models.DateField(blank=True, null=True)),
                ('status', models.IntegerField(choices=[(0, 'Draft'), (1, 'Published')], default=0)),
                ('MetaTitle', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('MetaDescription', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('MetaKeywords', models.CharField(blank=True, default='', max_length=255, null=True)),
            ],
            options={
                'ordering': ['-PostedDate'],
            },
        ),
    ]
