# Generated by Django 4.2.26 on 2025-11-14 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DT7App', '0007_jobpost'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobpost',
            name='ShortDescription',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
    ]
