# Generated by Django 4.2.26 on 2025-11-14 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DT7App', '0009_jobapplication'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobpost',
            name='Department',
            field=models.CharField(blank=True, choices=[('Web Design and Development', 'Web Design and Development'), ('Designers', 'Designers'), ('Social Media Marketing', 'Social Media Marketing'), ('E-commerce', 'E-commerce'), ('Email Marketing', 'Email Marketing'), ('Ecommerce Listing', 'Ecommerce Listing'), ('SEO Optimization', 'SEO Optimization'), ('Performance Marketing', 'Performance Marketing'), ('Full Stack Developer', 'Full Stack Developer')], max_length=100, null=True),
        ),
    ]
