# Generated by Django 5.2.6 on 2025-11-20 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DT7App', '0010_alter_jobpost_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapplication',
            name='phone',
            field=models.CharField(default=123456789, max_length=13, null=True),
        ),
        migrations.AlterField(
            model_name='jobpost',
            name='Department',
            field=models.CharField(blank=True, choices=[('Web Design and Development', 'Web Design and Development'), ('Designers', 'Designers'), ('Mobile App Developer', 'Mobile App Developer'), ('Social Media Marketing', 'Social Media Marketing'), ('E-commerce', 'E-commerce'), ('Email Marketing', 'Email Marketing'), ('Ecommerce Listing', 'Ecommerce Listing'), ('SEO Optimization', 'SEO Optimization'), ('Performance Marketing', 'Performance Marketing'), ('Full Stack Developer', 'Full Stack Developer')], max_length=100, null=True),
        ),
    ]
