# Generated by Django 5.2.6 on 2025-11-20 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DT7App', '0011_jobapplication_phone_alter_jobpost_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobapplication',
            name='phone',
            field=models.CharField(default='', max_length=13, null=True),
        ),
    ]
