# Generated by Django 5.2.6 on 2025-11-20 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DT7App', '0012_alter_jobapplication_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='jobpost',
            name='skills_required',
            field=models.ManyToManyField(blank=True, to='DT7App.skill'),
        ),
    ]
