# Generated by Django 5.2.6 on 2025-11-20 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DT7App', '0013_skill_jobpost_skills_required'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobpost',
            name='skills_required',
        ),
        migrations.AddField(
            model_name='jobpost',
            name='Requirements',
            field=models.TextField(blank=True, help_text='Enter required skills separated by commas ', null=True),
        ),
        migrations.DeleteModel(
            name='Skill',
        ),
    ]
