# Generated by Django 5.2.6 on 2025-11-20 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DT7App', '0015_skill_remove_jobpost_requirements_jobpost_skills'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobpost',
            name='skills',
        ),
        migrations.AddField(
            model_name='jobpost',
            name='Requirements',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='Skill',
        ),
    ]
