# Generated by Django 6.1.1 on 2026-09-26 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DT7App', '0016_remove_jobpost_skills_jobpost_requirements_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='VisitorTracking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visitor_id', models.CharField(db_index=True, help_text='Unique Visitor ID', max_length=100, unique=True)),
                ('visit_count', models.IntegerField(default=1, help_text='Total visit count / sessions')),
                ('device_type', models.CharField(default='Desktop', help_text='Mobile, Tablet, or Desktop', max_length=50)),
                ('traffic_source', models.CharField(blank=True, default='Direct', help_text='Referrer domain or campaign source', max_length=255)),
                ('pages_viewed', models.JSONField(blank=True, default=list, help_text='List of pages viewed by visitor')),
                ('exit_page', models.CharField(blank=True, default='', help_text='Last visited page', max_length=255)),
                ('scroll_depth', models.IntegerField(default=0, help_text='Maximum scroll depth percentage (0-100)')),
                ('ip_address', models.CharField(blank=True, help_text='Visitor IP address', max_length=45, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Visitor Tracking',
                'verbose_name_plural': 'Visitor Trackings',
                'ordering': ['-updated_at'],
            },
        ),
    ]
