# Generated by Django 6.1.1 on 2026-09-26 10:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DT7App', '0017_visitortracking'),
    ]

    operations = [
        migrations.CreateModel(
            name='VisitorPageHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_url', models.CharField(db_index=True, help_text='URL or Path visited', max_length=500)),
                ('page_title', models.CharField(blank=True, default='', help_text='Title of the visited page', max_length=255)),
                ('scroll_depth', models.IntegerField(default=0, help_text='Scroll depth percentage achieved on this page (0-100)')),
                ('time_spent', models.IntegerField(default=0, help_text='Time spent on page in seconds')),
                ('ip_address', models.CharField(blank=True, help_text='IP address at time of visit', max_length=45, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Visit timestamp')),
                ('visitor', models.ForeignKey(help_text='Associated Visitor', on_delete=django.db.models.deletion.CASCADE, related_name='page_history', to='DT7App.visitortracking')),
            ],
            options={
                'verbose_name': 'Visitor Page History',
                'verbose_name_plural': 'Visitor Page Histories',
                'ordering': ['-timestamp'],
            },
        ),
    ]
