# Generated by Django 6.1.1 on 2026-09-26 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DT7App', '0018_visitorpagehistory'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpamSubmissionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('form_name', models.CharField(help_text='Form Name (Contact, Enquiry, Career, etc.)', max_length=100)),
                ('name', models.CharField(blank=True, default='', max_length=255)),
                ('email', models.CharField(blank=True, default='', max_length=255)),
                ('ip_address', models.CharField(blank=True, max_length=45, null=True)),
                ('reason', models.CharField(help_text='Reason why submission was blocked (Honeypot, Time Trap, Keyword Spam, Rate Limit)', max_length=255)),
                ('submitted_data', models.JSONField(blank=True, default=dict, help_text='Raw payload of the blocked spam submission')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Spam Submission Log',
                'verbose_name_plural': 'Spam Submission Logs',
                'ordering': ['-created_at'],
            },
        ),
    ]
